FLASK_APP=run.py
FLASK_DEBUG=True
SECRET_KEY=tripanazomigambiyetsiz
PROPOGATE_EXCEPTIONS=True
API_TITLE="Eğitim REST API"
API_VERSION=v1
OPENAPI_VERSION=3.0.3
OPENAPI_URL_PREFIX=/
OPENAPI_SWAGGER_UI_PATH=/swagger-ui
OPENAPI_SWAGGER_UI_URL=https://cdn.jsdelivr.net/npm/swagger-ui-dist/
DATABASE_URL=0
SQLALCHEMY_TRACK_MODIFICATIONS=False

